name: MCOptimizer
version: '1.2.2'
main: com.mc.optimizer.OptimizerPlugin
api-version: '26.2'
description: A versatile Minecraft server optimization plugin enhancing server performance through smart resource management for both Paper and Spigot servers
authors: [juicyyfruittsnackss]
website: https://dsc.gg/fruitsnacks
bootstrapper: com.mc.optimizer.MCOptimizerBootstrap
load: STARTUP
dependencies:
  - name: Geyser-Spigot
    required: false
  - name: floodgate
    required: false
  - name: ViaVersion
    required: false
  - name: ProtocolSupport
    required: false
